---

# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'mrus11211280_fold0_bs4_dsbnwithedge_ch16_combo_1_1_1_l2_1e-4_adam_1e-4_poly_2x40_0.6_finetunev1_main1_aux0.6_prior10_s1.5t1_r1d1.5nodm_edge0_avgada3_pre10regression1_group_mse_amp_2080Ti'
phase : 'test'
test_name : 'centercrop_postprocess'

network_type : 'finetunev1'
# finetunev1 finetunev2 regression
local_gpu : 1
visible_gpu :  '0,1,2,3'

revert : false
do_connected_component : true
minimum_valid_object_size : 40

save_visuals : True
deterministic : True
DEBUG : False
verbose : false

fold : 0
weight_name : '79_net_mrus11211280_fold0_bs4_dsbnwithedge_ch16_combo_1_1_1_l2_1e-4_adam_1e-4_poly_2x40_0.6_finetunev1_main1_aux0.6_prior10_s1.5t1_r1d1.5nodm_edge0_avgada3_pre10regression1_group_mse_amp_2080Ti.pth'
weight_on_dir : false


#single : false
#gpu_ids : [0,1]
#phase_list : ['train', 'test']

# ---------------------------------------------------------------------------- #
# data
# ---------------------------------------------------------------------------- #
# dataset
dataset_name : 'mrusplusplus'
dataroot : './traces/datasets/MR-USvia20-full-11211280'
serial_batches: True
custom : true
preprocess : 'centercrop'
#   'centercrop'
#    'resize'
#   'zoom_centercrop'
crop_size : [112, 112, 80]
target_size : [112, 112, 80]
source_crop_size : [112, 112, 80]
target_crop_size : [112, 112, 80]
order_data: 3
order_seg: 1
scale : [0.8, 0.8, 0.8]
# dataloader
num_threads : 8

# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
model_name : 'dsbnpluswithauxtask'

input_nc : 1
output_nc : 1
init_channel_number : 16
up_interpolate: True
# ---------------------------------------------------------------------------- #
# path
# ---------------------------------------------------------------------------- #

logs_dir : './traces/logs/Exp1/DSBNPlusWithEdge'
checkpoints_dir : './traces/checkpoints/Exp1/DSBNPlusWithEdge'
results_dir : './traces/results/Exp1/DSBNPlusWithEdge'

# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
metric_names : ['basic_metrics', 'dice', 'recall', 'precision', 'specificity', 'accuracy', 'hd', 'hd95', 'asd', 'assd', 'ravd', 'roisize']
visual_names : ['volume', 'predict', 'label']


...
