---

# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'mrus11211280_fold1_bs4_DualStreamV1_ch16_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_3x400_0.6_2080Ti'
phase : 'test'
test_name : 'centercrop_postprocess'

local_gpu : 2
visible_gpu :  '0,1,2,3'

revert : false
do_connected_component : true
minimum_valid_object_size : 40

save_visuals : true
deterministic : True
DEBUG : False
verbose : false

fold : 1
network_type : 'V1'
weight_name : 'latest_net_mrus11211280_fold1_bs4_DualStreamV1_ch16_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_3x400_0.6_2080Ti.pth'
weight_on_dir : false

#single : false
#gpu_ids : [0,1]
#phase_list : ['train', 'test']

# ---------------------------------------------------------------------------- #
# data
# ---------------------------------------------------------------------------- #
# dataset
dataset_name : 'mrus'
dataroot : './traces/datasets/MR-USvia20-full-11211280'
serial_batches: True
custom : true
preprocess : 'centercrop'
#   'centercrop'
#    'resize'
#   'zoom_centercrop'
crop_size : [112, 112, 80]
target_size : [112, 112, 80]
source_crop_size : [112, 112, 80]
target_crop_size : [112, 112, 80]
order_data: 3
order_seg: 1
scale : [0.8, 0.8, 0.8]
# dataloader
num_threads : 8

# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
model_name : 'dualstream'
input_nc : 1
output_nc : 1
init_channel_number : 16
up_interpolate: True
# ---------------------------------------------------------------------------- #
# path
# ---------------------------------------------------------------------------- #

#logs_dir : './traces/logs/SingleOne'
#checkpoints_dir : './traces/checkpoints/SingleOne'
#results_dir : './traces/results/SingleOne'
logs_dir : './traces/logs/PhaseBaseLine/DualStream'
results_dir : './traces/results/PhaseBaseLine/DualStream'
checkpoints_dir : './traces/checkpoints/PhaseBaseLine/DualStream'

# SingleBoth DualStream
# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
metric_names : ['basic_metrics', 'dice', 'recall', 'precision', 'specificity', 'accuracy', 'hd', 'hd95', 'asd', 'assd', 'ravd', 'roisize']
visual_names : ['volume', 'predict', 'label']


...
