---
# 主要改weight_name、crop_size、stride、fold等
# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'mrusus11211280_patch_fold0_bs4_single_ch32_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_2x400_0.6'
phase : 'test'
test_name : 'crop969680_slide161616_nopad_noaug_nogauus_postprocess_1000'

local_gpu : 2
visible_gpu : '0,1,2,3'
# '0,''1,''2,''3,''4,''5,''6,''7'    "'0,1,2,3'"

DEBUG : False
verbose : false
save_visuals : True
deterministic : True

no_augment : True
compute_pad : False
use_gauusion_kernel : false
do_connected_component : true
minimum_valid_object_size : 40

gpu_ids : [2, 3]
phase_list : ['train', 'test']
# ---------------------------------------------------------------------------- #
# data
# ---------------------------------------------------------------------------- #
# dataset
dataset_name : 'mrusus'
fold : 0

crop_size : [96, 96, 80]
target_size : [96, 96, 80]
stride : [16, 16, 16]

# dataloader
batch_size : 8
num_threads : 16
# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
model_name : 'unet3d'
input_nc : 1
output_nc : 1
init_channel_number : 16
up_interpolate : False
conv_order : 'cbl'
# ---------------------------------------------------------------------------- #
# path
# ---------------------------------------------------------------------------- #
dataroot :  './traces/datasets/MR-USvia20-full-11211280'
# MR-USvia20-full-11211280  MR-USviaFenster20-pre128
weight_name : 'latest_net_mrusus11211280_patch_fold0_bs16_single_ch16_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_2x400_0.6_baseline_2080Ti.pth'
weight_dir  : './traces/checkpoints/PhaseBaseLine/SinglePatch/mrusus11211280_patch_fold0_bs16_single_ch16_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_2x400_0.6_baseline_2080Ti'
weight_on_dir : false
logs_dir : './traces/logs/PhaseBaseLine/SinglePatch'
checkpoints_dir : './traces/checkpoints/PhaseBaseLine/SinglePatch'
results_dir : './traces/results/PhaseBaseLine/SinglePatch'
# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
metric_names : ['dice', 'recall', 'precision', 'specificity', 'accuracy', 'hd', 'hd95', 'asd', 'assd', 'ravd']
visual_names : ['segment', 'label', 'origin_volume']
# 'origin_volume'
# 'basic_metrics',


...
