---
# 主要改weight_path、fold、preprocess、crop_size、target_size、save_visuals、revert、local_gpu、predict_name
# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'mrusmr11211280_whole_fold0_bs4_single_ch16_combo_1_1_1.5_l2_1e-4_adam_1e-4_poly_2x400_0.6_2080Ti'
phase : 'test'
predict_name : 'postprocess'

local_gpu : 2
visible_gpu :  '0,1,2,3'
# !!str "'0,''1,''2,''3,''4,''5,''6,''7'"

revert : false
do_connected_component : true
minimum_valid_object_size : 40

save_visuals : True
deterministic : True
single : Ture
DEBUG : False
verbose : false

gpu_ids : [0,1]
phase_list : ['train', 'test']
# ---------------------------------------------------------------------------- #
# data
# ---------------------------------------------------------------------------- #
# dataset
dataset_name : 'mrusmr'
fold : 0
custom : true
preprocess : ''
#   'centercrop'
#    'resize'
#   'zoom_centercrop'
crop_size : [128, 128, 96]
target_size : [128, 128, 96]
order_data: 3
order_seg: 1
scale : [0.8, 0.8, 0.8]
# dataloader
num_threads : 8
batch_size : 1
# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
model_name : 'unet3d'
input_nc : 1
output_nc : 1
init_channel_number : 16
up_interpolate : False
conv_order : 'cbl'
# ---------------------------------------------------------------------------- #
# path
# ---------------------------------------------------------------------------- #
dataroot : './traces/datasets/MR-USvia20-full-11211280'

weight_path : './traces/checkpoints/PhaseBaseLine/SinglePatch/mrusmr11211280_whole_fold4_bs4_single_ch16_combo_1_1_1_l2_1e-4_adam_1e-4_poly_3x300_0.6_OrdinaryAug_1080Ti/latest_net_mrusus11211280_whole_fold4_bs4_single_ch16_combo_1_1_1_l2_1e-4_adam_1e-4_poly_3x300_0.6_OrdinaryAug_1080Ti.pth'
weight_dir : './traces/checkpoints/PhaseBaseLine/SinglePatch/mrusmr11211280_whole_fold4_bs4_single_ch16_combo_1_1_1_l2_1e-4_adam_1e-4_poly_3x300_0.6_OrdinaryAug_1080Ti'
weight_on_dir : false
#
logs_dir : './traces/logs/PhaseBaseLine/SinglePatch'
checkpoints_dir : './traces/checkpoints/PhaseBaseLine/SinglePatch'
results_dir : './traces/results/PhaseBaseLine/SinglePatch'

# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
metric_names : ['basic_metrics', 'dice', 'recall', 'precision', 'specificity', 'accuracy', 'hd', 'hd95', 'asd', 'assd', 'ravd']
visual_names : ['segment', 'label', 'volume']


# 'basic_metrics',
...

