---
#'''
#三级配置文件----第二级
#提供特定的数据集和模型训练时所需要的参数，并提供一些不再改变的固定参数值
#'''

# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'trus_unet3d_test_horovod'
dataset_name : 'trus'
model_name : 'unet3d'
gpu_ids : [2, 3]
visible_gpu : !!str "'0,''1,''2,''3'"
deterministic : False
# ---------------------------------------------------------------------------- #
# distribution
# ---------------------------------------------------------------------------- #
DP : False
DDP : False
HOROVOD : True
APEX : False
SyncBatchNorm : False
world_size : -1
rank : -1
local_rank : -1
dist_url : 'env://'
# ---------------------------------------------------------------------------- #
# horovod
# ---------------------------------------------------------------------------- #


# ---------------------------------------------------------------------------- #
# dataset
# ---------------------------------------------------------------------------- #
# dataset
dataroot : './traces/datasets/prostate_daf3d_pre'
phase : 'train'
serial_batches : true
custom : true
preprocess : 'randomscale_randomcrop_ranomrotate_centercrop_rot90_mirror_gaussianNoise_GaussianBlur_BrightnessMultiplicative_contrast_simulate_gammatransform'
crop_size : [128, 128, 128]
target_size : [128, 128, 128]
scale : [1., 1., 1.]
bright_mu : 0.1
bright_sigma : 0.5
elastic_alpha : [0., 1000]
elastic_sigma : [10., 13.]
shift_mu : [0., 1000]
shift_sigma : [10., 13.]

# dataloader
num_threads : 8
batch_size : 4
# ---------------------------------------------------------------------------- #
# module
# ---------------------------------------------------------------------------- #
# model
input_nc : 1
output_nc : 1
init_channel_number : 32
up_interpolate : False
conv_order : 'crb'
# loss
reduction : 'mean'
ignore_index : ~
smooth : 0
# initialization
init_type : 'kaiming'
init_gain : 1.4142135623730951
init_std : 0.02
# ---------------------------------------------------------------------------- #
# optimizer
# ---------------------------------------------------------------------------- #
# optimizer
optimizer_name : adam
lr : 1e-3
weight_decay : 0
# scheduler
lr_policy : 'step'
decay_epochs : 30
decay_rate : 0.5
warmup_lr : 2e-7
warmup_epochs : 5
lr_noise : ~
# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
weight_path : './traces/checkpoints/trus_unet3d_testDDP_TEST_forDDP/11_net_trus_unet3d_testDDP_TEST_forDDP.pth'
continue_train : false
verbose : true
# additional
suffix : ''
DEBUG : False
epoch_start : 1
num_epochs : 100
isTrain : True

# ---------------------------------------------------------------------------- #
# train
# ---------------------------------------------------------------------------- #
# network saving and loading
save_epoch_start : 1
save_epoch_freq : 5
save_iter_start : 5000
save_iter_freq : 500
save_by_iter : false
# network print and showing
display_freq : 4
print_freq : 1
plot_freq : 1
val_epoch_freq : ~
test_on_train : false

# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : False




...