---
# ---------------------------------------------------------------------------- #
# basic
# ---------------------------------------------------------------------------- #
name : 'ummkd_19219248_bs4_ch16_kaiming_1.5_1_1_adam_2e-4_cosine_1.0_0.3_2x500_warmup_10_1e-5_v1'
# 规则：数据集名+网络名+训练策略+数据集参数+网络参数+学习率策略
#
# 训练策略： DDP/DP、SyncBatchNorm、use_mixed_precision、use_gradient_accumulation、APEX
dataset_name : 'mrusdiff'
model_name : 'ummkd'
gpu_ids : [0, 1, 2, 3, 4, 5, 6, 7]
batch_size : 1
visible_gpu : !!str "'1,2,4'"
# '0,''1,''2,''3'
DEBUG : False
deterministic : True
# ---------------------------------------------------------------------------- #
# tricks
# ---------------------------------------------------------------------------- #
use_mixed_precision : False
use_gradient_accumulation : False
gradient_accumulation_k_step : 1
# DDP
single : False
DP : False
DDP : False
SyncBatchNorm : True
world_size : 4
rank : 0
local_rank : -1
dist_url : 'tcp://127.0.0.1:52001'
# 'env://'
# ---------------------------------------------------------------------------- #
# dataset
# ---------------------------------------------------------------------------- #
# dataset
dataroot : './traces/datasets/MR-USviaFenster20_pre_v3'
phase : 'train'
serial_batches : true
data_shuffle : true
custom : true
preprocess : 'elastic_randomscale_randomcrop_ranomrotate_centercrop_rot90_mirror_gaussianNoise_GaussianBlur_BrightnessMultiplicative_contrast_simulate_gammatransform'
#
#
crop_size : [176, 176, 160]
source_crop_size : [192,192,48]
target_crop_size : [192,192,160]
target_size : [196, 192, 160]
#scale: [1, 1, 1]
rot_axes: [1, 2]
mirror_axes: [1, 2]
rot_angle_spectrum: 25
scale_range : [0.8, 1.2]
order_data: 3
order_seg: 1
#bright_mu : 0.0
#bright_sigma : 0.1
elastic_alpha : [0., 900]
elastic_sigma : [9., 13.]
#shift_mu : [0., 1000]
#shift_sigma : [10., 13.]
g_noise_variance: [0.3, 0.7]

# dataloader
num_threads : 8
drop_last : False
# ---------------------------------------------------------------------------- #
# module
# ---------------------------------------------------------------------------- #
# model
input_nc : 1
output_nc : 1
init_channel_number : 16
up_interpolate : False
conv_order : 'cbl'
# loss
loss_name: 'combo'
loss_alpha : 1.0
loss_beta : 1.0
loss_gamma : 1.0
loss_weight : 1.0
loss_eps : 1e-7
loss_smooth : 1.0
reduction : 'mean'
ignore_index : -100
# initialization
init_type : 'kaiming'
init_gain : 1.4142135623730951
init_std : 0.02
# ---------------------------------------------------------------------------- #
# optimizer
# ---------------------------------------------------------------------------- #
# optimizer
lr : 2e-4
optimizer_name : 'adam'

# scheduler
lr_policy : 'cosine'

warmup_lr : 1e-5
warmup_epochs : 10
warmup_prefix : True

lr_noise : ~
lr_noise_pct : 0.67
lr_noise_std : 1.

lr_cycle_mul : 1.0
lr_cycle_decay : 0.3
lr_cycle_limit : 2
cooldown_epochs : 5

min_lr : 1e-7
lr_k_decay : 1.0
decay_epochs : 100
decay_rate : 0.3
eval_metric : ''
patience_epochs : 20
# ---------------------------------------------------------------------------- #
# model
# ---------------------------------------------------------------------------- #
weight_path : './traces/checkpoints/......'
optimizer_path : ~
continue_train : false
verbose : false
# additional
suffix : ''
epoch_start : 1
num_epochs : 500
isTrain : True

# ---------------------------------------------------------------------------- #
# train
# ---------------------------------------------------------------------------- #
# network saving and loading
save_epoch_start : 1
save_epoch_freq : 1
save_iter_start : 50000
save_iter_freq : 500
save_by_iter : false
# network print and showing
display_freq : 12
print_freq : 1
plot_freq : 1

val_epoch_freq : 1
test_on_train : true

# visualer
with_tensorboard : True
save_log : True
save_visuals : True
save_only_latest : True
save_visuals_frep : 1
draw_model : False
display_on_tensorboard: False
display_histogram: False
play_video : False

# ---------------------------------------------------------------------------- #
# test
# ---------------------------------------------------------------------------- #
eval : True
test_data_phase : 'test'
test_preprocess : 'centercrop'
# resize centercrop
# 56057    760337
# 2949120  2949120
# 0.0190    0.2578
test_batchsize : 1


...

#             [0.5, 1]   0.01
# noise_args: lr_noise lr_noise_pct lr_noise_std seed
# warmup_args: warmup_lr warmup_epochs warmup_prefix
# cycle_args: lr_cycle_mul lr_cycle_decay lr_cycle_limit
# other_args: num_epochs min_lr  lr_k_decay  cooldown_epochs decay_rate decay_epochs patience_epochs eval_metric

#    cosine:  num_epochs min_lr  lr_k_decay  cooldown_epochs
#      tanh:  num_epochs min_lr              cooldown_epochs
#      poly:  num_epochs min_lr  lr_k_decay  cooldown_epochs decay_rate
#    linear:             min_lr                                         decay_epochs
#      step:                                                 decay_rate decay_epochs
# multistep:                                                 decay_rate decay_epochs
#   plateau:             min_lr                              decay_rate              patience_epochs eval_metric