[loggers]
keys=root,main

[handlers]
keys=fileHandler,streamHandler

[formatters]
keys=fmt

[filters]
keys=


[logger_root]
level=DEBGU
handlers=streamHandler

[logger_main]
handlers=fileHandler
level=DEBGU
qualname=main

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=fmt
args=('tst.log','a',20000,5,)

[handler_streamHandler]
class=StreamHandler
level=DEBUG
formatter=fmt
args=(sys.stdout,)

[formatter_fmt]
format=%(asctime)s - %(name)s - %(levelname)s - % (message)s
datefmt=



