#!/bin/bash
set -ex


rsync -rvP  --update --ignore-existing  lf@172.21.141.5:/home/lf/Documents/CODE/NewDoing/UMMS/traces/  /data/fong/CODE/PycharmProject/UMMS/traces/

rsync -rvP  --update --ignore-existing  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/  /data/fong/CODE/PycharmProject/UMMS/traces/

rsync -rvP  --update --ignore-existing  lf@172.21.114.159:/home/lf/ProjectRepository/CODE/NewDoing/UMMS/traces/  /data/fong/CODE/PycharmProject/UMMS/traces/

rsync -rvP  --update --ignore-existing  /data/fong/CODE/PycharmProject/UMMS/traces/  lf@172.21.141.5:/home/lf/Documents/CODE/NewDoing/UMMS/traces/

rsync -rvP  --update --ignore-existing  /data/fong/CODE/PycharmProject/UMMS/traces/  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/

rsync -rvP  --update --ignore-existing   /data/fong/CODE/PycharmProject/UMMS/traces/  lf@172.21.114.159:/home/lf/ProjectRepository/CODE/NewDoing/UMMS/traces/


# 8cup
# rsync -rvP  --update --ignore-existing  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/  /home/lf/Documents/CODE/NewDoing/UMMS/traces/
# rsync -rvP  --update --ignore-existing  /home/lf/Documents/CODE/NewDoing/UMMS/traces/  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/
#

# Amax
# rsync -rvP  --update --ignore-existing  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/  /home/lf/ProjectRepository/CODE/NewDoing/UMMS/traces/
# rsync -rvP  --update --ignore-existing  /home/lf/ProjectRepository/CODE/NewDoing/UMMS/traces/  lf@172.21.141.4:/data/project_data_lf/CODE/PycharmProjects/UMMS/traces/


# 3cup
# rsync -rvP  --update --ignore-existing lf@172.21.114.159:/home/lf/ProjectRepository/CODE/NewDoing/UMMS/traces/ /data/project_data_lf/CODE/PycharmProjects/UMMS/traces/


